# Generated by Django 5.0.6 on 2024-07-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niinii', '0002_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gmail',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
